version: "3.8"

services:
  db:
    image: postgres:latest
    container_name: jumia_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: jumia
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always

  web:
    build: .
    container_name: jumia_app
    depends_on:
      - db
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=postgresql://postgres:root@db:5432/jumia
    command: python app.py
